### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by daliusd** [jlfwong/vim-mercenary#3]
Tried running this on Windows. There are number of issues:
- Assumes that I'm using default shell (cmd.exe) that does not contain spaces.
- Uses *nix syntax to pass env variables (HGPLAIN) that does not work in Windows.
- Other path problems while formatting command.

I guess there are more problems but I simply gave up trying to fix this at this stage as I'm not active hg user.

**Comment by jlfwong** [comment]
Thanks for the report! This project isn't actively maintained, and I haven't used it since 2012. I'll leave this issue open in case someone else is interested in tackling this.

**Comment by daliusd** [comment]
Moved to non Windows company. Problem solved 😄
